# Generated by Django 2.0.6 on 2018-07-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('authorization_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=32)),
                ('corporate_url', models.CharField(help_text='a list of urls, stored as json', max_length=256, null=True)),
                ('status', models.CharField(choices=[('g', 'Granted'), ('r', 'Rejected'), ('p', 'Pending')], default='p', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=32)),
                ('admin', models.IntegerField(default=0)),
                ('group_auth', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GroupAuth.Authorization')),
            ],
        ),
    ]
