# Generated by Django 2.0.5 on 2018-07-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, null=True)),
                ('intro', models.CharField(max_length=512, null=True)),
                ('essay_request', models.CharField(max_length=512, null=True)),
                ('ddl_date', models.DateTimeField(null=True)),
                ('result_notice_date', models.DateTimeField(null=True)),
                ('regist_attend_date', models.DateTimeField(null=True)),
                ('meeting_date', models.DateTimeField(null=True)),
                ('meeting_end_date', models.DateTimeField(null=True)),
                ('schedule', models.CharField(max_length=128, null=True)),
                ('organization', models.CharField(max_length=128, null=True)),
                ('template', models.CharField(max_length=64, null=True)),
                ('receipt', models.FloatField(null=True)),
                ('support', models.CharField(max_length=128, null=True)),
                ('about_us', models.CharField(max_length=128, null=True)),
                ('institution', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Institution.Institution')),
            ],
        ),
    ]
