# Generated by Django 2.0.5 on 2018-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Meeting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('favorite', models.ManyToManyField(blank=True, related_name='User_set', to='Meeting.Meeting')),
                ('participate', models.ManyToManyField(blank=True, related_name='Attendee_set', to='Meeting.Meeting')),
            ],
        ),
    ]
