package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * AbsenceId generated by hbm2java
 */
public class AbsenceId implements java.io.Serializable {

	private int id;
	private Date date;

	public AbsenceId() {
	}

	public AbsenceId(int id, Date date) {
		this.id = id;
		this.date = date;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbsenceId))
			return false;
		AbsenceId castOther = (AbsenceId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
