package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Absence generated by hbm2java
 */
public class Absence implements java.io.Serializable {

	private AbsenceId id;
	private String stuName;
	private Integer groupId;

	public Absence() {
	}

	public Absence(AbsenceId id, String stuName) {
		this.id = id;
		this.stuName = stuName;
	}

	public Absence(AbsenceId id, String stuName, Integer groupId) {
		this.id = id;
		this.stuName = stuName;
		this.groupId = groupId;
	}

	public AbsenceId getId() {
		return this.id;
	}

	public void setId(AbsenceId id) {
		this.id = id;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

}
