package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private int studentId;
	private int groupId;
	private byte status;

	public Application() {
	}

	public Application(int studentId, int groupId, byte status) {
		this.studentId = studentId;
		this.groupId = groupId;
		this.status = status;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
