package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Attendance generated by hbm2java
 */
public class Attendance implements java.io.Serializable {

	private int id;
	private int checked;
	private String name;
	private int group;

	public Attendance() {
	}

	public Attendance(int id, int checked, String name, int group) {
		this.id = id;
		this.checked = checked;
		this.name = name;
		this.group = group;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getChecked() {
		return this.checked;
	}

	public void setChecked(int checked) {
		this.checked = checked;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getGroup() {
		return this.group;
	}

	public void setGroup(int group) {
		this.group = group;
	}

}
