package model;
// Generated 2017-7-3 9:50:10 by Hibernate Tools 5.2.1.Final

/**
 * GradeId generated by hbm2java
 */
public class GradeId implements java.io.Serializable {

	private int courseId;
	private int studentId;

	public GradeId() {
	}

	public GradeId(int courseId, int studentId) {
		this.courseId = courseId;
		this.studentId = studentId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GradeId))
			return false;
		GradeId castOther = (GradeId) other;

		return (this.getCourseId() == castOther.getCourseId()) && (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseId();
		result = 37 * result + this.getStudentId();
		return result;
	}

}
