package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private int id;
	private double mark;

	public Grade() {
	}

	public Grade(int id, double mark) {
		this.id = id;
		this.mark = mark;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public double getMark() {
		return this.mark;
	}

	public void setMark(double mark) {
		this.mark = mark;
	}

}
