package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * GroupMemberId generated by hbm2java
 */
public class GroupMemberId implements java.io.Serializable {

	private int memberId;
	private int groupId;

	public GroupMemberId() {
	}

	public GroupMemberId(int memberId, int groupId) {
		this.memberId = memberId;
		this.groupId = groupId;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupMemberId))
			return false;
		GroupMemberId castOther = (GroupMemberId) other;

		return (this.getMemberId() == castOther.getMemberId()) && (this.getGroupId() == castOther.getGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberId();
		result = 37 * result + this.getGroupId();
		return result;
	}

}
