package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Resources generated by hbm2java
 */
public class Resources implements java.io.Serializable {

	private int id;
	private byte[] path;

	public Resources() {
	}

	public Resources(int id, byte[] path) {
		this.id = id;
		this.path = path;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte[] getPath() {
		return this.path;
	}

	public void setPath(byte[] path) {
		this.path = path;
	}

}
