package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * ScoreId generated by hbm2java
 */
public class ScoreId implements java.io.Serializable {

	private int memId;
	private int checkedId;

	public ScoreId() {
	}

	public ScoreId(int memId, int checkedId) {
		this.memId = memId;
		this.checkedId = checkedId;
	}

	public int getMemId() {
		return this.memId;
	}

	public void setMemId(int memId) {
		this.memId = memId;
	}

	public int getCheckedId() {
		return this.checkedId;
	}

	public void setCheckedId(int checkedId) {
		this.checkedId = checkedId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScoreId))
			return false;
		ScoreId castOther = (ScoreId) other;

		return (this.getMemId() == castOther.getMemId()) && (this.getCheckedId() == castOther.getCheckedId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemId();
		result = 37 * result + this.getCheckedId();
		return result;
	}

}
