package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Score generated by hbm2java
 */
public class Score implements java.io.Serializable {

	private ScoreId id;
	private double score;

	public Score() {
	}

	public Score(ScoreId id, double score) {
		this.id = id;
		this.score = score;
	}

	public ScoreId getId() {
		return this.id;
	}

	public void setId(ScoreId id) {
		this.id = id;
	}

	public double getScore() {
		return this.score;
	}

	public void setScore(double score) {
		this.score = score;
	}

}
