package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int id;
	private String name;
	private byte gender;

	public Student() {
	}

	public Student(int id, String name, byte gender) {
		this.id = id;
		this.name = name;
		this.gender = gender;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte getGender() {
		return this.gender;
	}

	public void setGender(byte gender) {
		this.gender = gender;
	}

}
