package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * SubResouces generated by hbm2java
 */
public class SubResouces implements java.io.Serializable {

	private int id;
	private int taskId;
	private int resourcesId;
	private int groupId;

	public SubResouces() {
	}

	public SubResouces(int id, int taskId, int resourcesId, int groupId) {
		this.id = id;
		this.taskId = taskId;
		this.resourcesId = resourcesId;
		this.groupId = groupId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getResourcesId() {
		return this.resourcesId;
	}

	public void setResourcesId(int resourcesId) {
		this.resourcesId = resourcesId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

}
