package model;
// Generated 2017-7-4 19:51:05 by Hibernate Tools 5.2.1.Final

/**
 * Upload generated by hbm2java
 */
public class Upload implements java.io.Serializable {

	private Integer resourcesId;
	private String title;
	private String num;
	private int teacherId;
	private String ts;
	private String path;

	public Upload() {
	}

	public Upload(String title, int teacherId, String ts) {
		this.title = title;
		this.teacherId = teacherId;
		this.ts = ts;
	}

	public Upload(String title, String num, int teacherId, String ts, String path) {
		this.title = title;
		this.num = num;
		this.teacherId = teacherId;
		this.ts = ts;
		this.path = path;
	}

	public Integer getResourcesId() {
		return this.resourcesId;
	}

	public void setResourcesId(Integer resourcesId) {
		this.resourcesId = resourcesId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public String getTs() {
		return this.ts;
	}

	public void setTs(String ts) {
		this.ts = ts;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

}
