//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database1Entities : DbContext
    {
        public database1Entities()
            : base("name=database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignment> assignment { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<jiaowu> jiaowu { get; set; }
        public virtual DbSet<score> score { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<submission> submission { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<team> team { get; set; }
        public virtual DbSet<term> term { get; set; }
    }
}
