//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission
    {
        public int submission_id { get; set; }
        public Nullable<int> assignment { get; set; }
        public Nullable<int> team_id { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<System.DateTime> sub_time { get; set; }
        public Nullable<int> sub_count { get; set; }
        public string sub_path { get; set; }
    }
}
