# Generated by Django 2.0.5 on 2018-07-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('email', models.CharField(max_length=256, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('corporate_id', models.CharField(max_length=256, null=True)),
                ('establish_date', models.DateField(null=True)),
                ('place', models.CharField(max_length=256, null=True)),
                ('legal_person', models.CharField(max_length=256, null=True)),
                ('type', models.CharField(max_length=16, null=True)),
                ('status', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='institution',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Institution.Institution'),
        ),
    ]
